# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.IntegerField()),
                ('diagnosis_related_group', models.CharField(max_length=250)),
                ('avg_covered_charges', models.FloatField()),
                ('avg_total_payments', models.FloatField()),
                ('avg_medicare_payments', models.FloatField()),
            ],
        ),
    ]
