# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
